import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 9

[shell]
program = "zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.97

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
